### ISSUE TITLE
windows console encoding error: script stoped or didn't start

### ISSUE THREAD

**Issue by tohidlm** [wirthual/TelegramMathBattleSolver#1]
hi. thanks for this nice script. i use python 3.5.2 and follow your direction. i dont know anything about python but finish the steps.
now have a bad problem and cant solve it. script stop working after 2-3 answer or dont start to play game at all.it is for line22 module or operator or charmap.

**Comment by wirthual** [comment]
Hello,
did you use the script for python 3? And can you post the output of the console when the script is crashing?

**Comment by tohidlm** [comment]
yes.i take a picture from output and attach it.
![python error](https://cloud.githubusercontent.com/assets/22861908/19420302/8ea42ffe-93f5-11e6-984e-266092bbeda4.JPG)

**Comment by wirthual** [comment]
Mhh looks to me like a encoding problem in the windows console. Can you try to run this command before starting the script: chcp 65001

Got this hint from [here](http://stackoverflow.com/questions/32382686/unicodeencodeerror-charmap-codec-cant-encode-character-u2010-character-m).

**Comment by tohidlm** [comment]
thank you :)

**Comment by wirthual** [comment]
Resolved. Changed name to more meaningful.
