### ISSUE TITLE
lumberjack Bot

### ISSUE THREAD

**Issue by mehranexpert** [wirthual/TelegramMathBattleSolver#2]
Can u help me for this game

`http://199.127.99.211/games/game.html`

**Comment by wirthual** [comment]
Hi,
i uploaded a python file for lumberjack. But its made with absolute position of pixels so it will probably not work for you. Maybe you can adapt it for your needs.

https://github.com/wirthual/TelegramMathBattleSolver/blob/master/LumberjackBotSolver.py

Heres a video:
[![YT Video](http://img.youtube.com/vi/qKRjTQzQ7h4/0.jpg)](http://www.youtube.com/watch?v=qKRjTQzQ7h4)

**Comment by hazrateadam** [comment]
Hi,
Thanks for your comment. Please could you give us tip that how we can set up absolute position of pixels?

**Comment by wirthual** [comment]
Sorry this is not very accurate and I also had to try out. Basically you check if the color on the other side of the man is blue like the sky: RGB(17,80,173) and if yes you press the button on this side.

**Comment by wirthual** [comment]
Closed because of inactivity
